#!/usr/bin/env python3
"""
Chrome Cookie Bridge — WSL/Linux cookie reader.

Reads cookies exported by the Chrome Cookie Bridge extension and outputs
them in Netscape format (curl/wget/yt-dlp compatible) or JSON.

Usage:
  python3 cookie_reader.py reddit.com              # Netscape format
  python3 cookie_reader.py reddit.com --json       # JSON format
  python3 cookie_reader.py reddit.com --netscape   # Netscape from JSON source
  python3 cookie_reader.py --list                  # List available domains
  python3 cookie_reader.py --check                 # Check file freshness

Files read from ~/Downloads/:
  hermes_cookies.json  — JSON export (preferred)
  hermes_cookies.txt   — Netscape fallback
"""

import json
import os
import sys
import time
from pathlib import Path

# --- Config ---
DOWNLOADS = Path(os.environ.get("USERPROFILE", Path.home() / "Downloads"))
# In WSL, Downloads is typically under /mnt/c/Users/<name>/Downloads
_WIN_USER = os.environ.get("WINDOWS_USER", "")
if not DOWNLOADS.exists() and _WIN_USER:
    DOWNLOADS = Path(f"/mnt/c/Users/{_WIN_USER}/Downloads")

# Fallback search
_SEARCH_PATHS = [
    DOWNLOADS,
    Path("/mnt/c/Users/user/Downloads"),
    Path.home() / "Downloads",
    Path("/mnt/c/Users") / os.environ.get("USER", "user") / "Downloads",
]

JSON_FILE = "hermes_cookies.json"
NETSCAPE_FILE = "hermes_cookies.txt"


def find_cookie_file(filename: str) -> Path | None:
    for base in _SEARCH_PATHS:
        p = base / filename
        if p.exists():
            return p
    return None


def load_cookies() -> tuple[list[dict], str, Path]:
    """Load from JSON first, fall back to Netscape. Returns (cookies, format, path)."""
    json_path = find_cookie_file(JSON_FILE)
    if json_path:
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                cookies = json.load(f)
            return cookies, "json", json_path
        except (json.JSONDecodeError, OSError) as e:
            pass  # fall through to Netscape

    netscape_path = find_cookie_file(NETSCAPE_FILE)
    if netscape_path:
        try:
            cookies = _parse_netscape(netscape_path)
            return cookies, "netscape", netscape_path
        except OSError:
            pass

    print(f"[ERROR] No cookie file found. Tried: {JSON_FILE}, {NETSCAPE_FILE}", file=sys.stderr)
    print(f"[HINT] Install 'Chrome Cookie Bridge' extension and run it once.", file=sys.stderr)
    sys.exit(1)


def _parse_netscape(path: Path) -> list[dict]:
    cookies = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) >= 7:
                cookies.append({
                    "domain": parts[0],
                    "name": parts[5],
                    "value": parts[6],
                    "path": parts[2],
                    "secure": parts[3] == "TRUE",
                    "httpOnly": False,
                    "sameSite": "unspecified",
                    "expirationDate": float(parts[4]) if parts[4] != "0" else None,
                })
    return cookies


def check_freshness():
    cookies, fmt, path = load_cookies()
    mtime = os.path.getmtime(str(path))
    age_min = (time.time() - mtime) / 60
    age_str = f"{age_min:.0f}m"
    
    if age_min > 120:
        print(f"STALE: {age_str} old ({path})")
        sys.exit(1)
    elif age_min > 60:
        print(f"WARN: {age_str} old ({path})")
        sys.exit(0)
    else:
        print(f"FRESH: {age_str} old · {len(cookies)} cookies · {path}")
        sys.exit(0)


def list_domains(cookies: list[dict]):
    domains = sorted(set(
        (c.get("domain", "") or "").lstrip(".") 
        for c in cookies if c.get("domain")
    ))
    for d in domains:
        count = sum(1 for c in cookies if (c.get("domain") or "").lstrip(".") == d)
        print(f"  {d} ({count} cookies)")


def filter_cookies(cookies: list[dict], domain: str) -> list[dict]:
    domain = domain.lower().strip()
    result = []
    for c in cookies:
        cd = (c.get("domain", "") or "").lower().lstrip(".")
        if cd == domain or cd.endswith("." + domain):
            result.append(c)
    return result


def to_netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by Chrome Cookie Bridge", ""]
    for c in cookies:
        domain = c.get("domain", "")
        if not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = str(int(c["expirationDate"])) if c.get("expirationDate") else "0"
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{c.get('name', '')}\t{c.get('value', '')}")
    return "\n".join(lines)


def to_cookie_header(cookies: list[dict]) -> str:
    return "; ".join(f"{c['name']}={c['value']}" for c in cookies if c.get("name") and c.get("value"))


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] in ("--help", "-h"):
        print(__doc__)
        sys.exit(0)

    if sys.argv[1] == "--check":
        check_freshness()

    cookies, fmt, path = load_cookies()

    if sys.argv[1] == "--list":
        list_domains(cookies)
        sys.exit(0)

    domain = sys.argv[1]
    filtered = filter_cookies(cookies, domain)

    if not filtered:
        print(f"[WARN] No cookies for: {domain}", file=sys.stderr)
        sys.exit(1)

    use_json = "--json" in sys.argv
    use_netscape = "--netscape" in sys.argv or not use_json

    if use_json:
        print(json.dumps(filtered, indent=2))
    
    if use_netscape:
        print(to_netscape(filtered))

    # Cookie header to stderr
    header = to_cookie_header(filtered)
    if header:
        print(f"# Cookie: {header[:200]}{'…' if len(header) > 200 else ''}", file=sys.stderr)
